# Use a node base image
FROM node:latest

# Set working directory for frontend service
WORKDIR /app/client

# Copy frontend package.json and install dependencies
COPY client/package*.json ./
RUN npm install

# Copy frontend source files
COPY client/ ./

# Expose the frontend service port
EXPOSE 3000

# Command to start the frontend app (assuming it starts on port 3000)
CMD ["npm", "start"]

