version: '3'

services:
  mongodb:
    image: mongo:latest
    networks:
      - IP-2-network
    ports:
      - "27017:27017" # Ensure MongoDB is accessible from outside the container for development purposes

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/backend
    networks:
      - IP-2-network
    env_file:
      - .env   # Load environment variables from .env file
    depends_on:
      - mongodb  # Ensure backend waits for MongoDB to be ready before starting

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "3001:3000"
    volumes:
      - ./client:/app/client
    networks:
      - IP-2-network
    env_file:
      - .env   # Load environment variables from .env file
    depends_on:
      - backend  # Ensure frontend waits for backend to be ready before starting

networks:
  IP-2-network:

