FROM node:latest
WORKDIR /app

# Copy package.json and package-lock.json
COPY client/package*.json ./client/
RUN cd client && npm install

# Copy all other client files
COPY client/. ./client/
COPY . .

EXPOSE 3000
CMD ["npm", "start"]

