version: '3'

services:
  mongodb:
    image: mongo:latest
    networks:
      - yolo_ip2_network
    ports:
      - "27017:27017"

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/backend
    networks:
      - yolo_ip2_network
    env_file:
      - .env   # Load environment variables from .env file

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "3001:3000"
    volumes:
      - ./client:/app/client
    networks:
      - yolo_ip2_network
    env_file:
      - .env   # Load environment variables from .env file

networks:
  yolo_ip2_network:
    driver: bridge

