version: '3'
services:
  # MongoDB Container (same as before)
  mongodb:
    container_name: mongo_ip2
    image: mongo:latest
    networks:
      - yolo_ip2_network
    volumes:
      - mongodb_data:/data/db

  # Node.js Backend Container (same as before)
  node:
    container_name: node_ip2
    image: node:latest
    networks:
      - yolo_ip2_network
    depends_on:
      - mongodb
    volumes:
      - ./app:/app

  # Frontend Container (using the React Dockerfile)
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - yolo_ip2_network

  # Ngrok Container (using the Ngrok Dockerfile)
  ngrok:
    build:
      context: . 
      dockerfile: Dockerfile-ngrok
    ports:
      - "4040:4040"  # Expose Ngrok web interface (optional)
    networks:
      - yolo_ip2_network

networks:
  yolo_ip2_network:
    external: true

volumes:
  mongodb_data:
    driver: local

