version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/backend
    networks:
      - IP-2-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "3001:3000"
    volumes:
      - ./client:/app/client
    networks:
      - IP-2-network

networks:
  IP-2-network:

