version: '3'
services:
  # MongoDB Container (using the existing container)
  mongodb:
    container_name: mongodb
    image: mongo:latest
    networks:
      - yolo_ip2_network
    volumes:
      - mongodb_data:/data/db

  # Node.js Backend Container (using the existing container)
  node_IP2:
    container_name: node_IP2
    image: node:latest
    networks:
      - yolo_ip2_network
    depends_on:
      - mongodb
    volumes:
      - ./app:/app

  # Frontend Container (React app served by Nginx)
  frontend_ip2:
    build:
      context: ./client/src  
      dockerfile: Dockerfile-frontend  
    ports:
      - "3000:3000"  
    networks:
      - yolo_ip2_network

networks:
  yolo_ip2_network:
    external: true

volumes:
  mongodb_data:
    driver: local

