version: '3'
services:
  # MongoDB Container
  mongo_ip2:
    container_name: mongo_ip2
    image: mongo:latest
    networks:
      - yolo_ip2_network
    volumes:
      - mongodb_data:/data/db

  # Node.js Backend Container
  node_ip2:
    container_name: node_ip2
    image: node:latest
    networks:
      - yolo_ip2_network
    depends_on:
      - mongo_ip2
    volumes:
      - ./app:/app

  # Frontend Container using Nginx
  nginx_ip2:
    container_name: nginx_ip2
    image: nginx:alpine
    ports:
      - "3000:80"
    networks:
      - yolo_ip2_network

networks:
  yolo_ip2_network:
    external: true

volumes:
  mongodb_data:
    driver: local

