version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-node
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - IP-2-network
    volumes:
      - ./client:/app/client  # Mount the client folder into the /app/client directory in the container
      - .:/app  # Mount the project root into the /app directory in the container
    volumes:
      - app-data:/app/data  # Mount the data volume for your app

  mongo:
    build:
      context: .
      dockerfile: Dockerfile-mongodb
    networks:
      - IP-2-network
    volumes:
      - mongo-data:/data/db

networks:
  IP-2-network:

volumes:
  app-data:
  mongo-data:


