# Use an official Node.js image as the base image for building the frontend
FROM node:latest as build

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY client/package*.json ./

# Install dependencies
RUN npm install

# Copy files from public/client/ to the container's /app/ directory
COPY client/ /app/

# Build the React app
RUN npm run build

